language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: v1CUlyADWw5K7j5yQSxPOHquShBzq6akV55LRKg9NPYo4s7USfjFOeJkpXqJE4Nt9nWLmlH/YeIZDyO3NFeU3Czv5ScBd5FRfri0XroivzmlbhGBIdPSm/kOObsQEwKslVRrFgRO2iuSeeL90aV8VRSxXyN424ax8imIGsi5/lZU7EmiPqJj6js4Z82Ko+GGk6zUj+YTK/GBNWYMg26ydG5MX14IwePrJxM51tYoN+paTS7oHVEELkZIBJn0JS1dywJWARLj+aLbsr45wj3w8yik/Du9yEMGGhJAckCEKgIfLTe6o96E4TQCoPhjkP6j5l4m5y1xgYzzWJhZ/h6z+xuhINdX+wlWYBSmIJy0FCC9nP8WFl5ont4O/ayf50YaXsqnVIgALpooEiORj7BSByh+b5NX1+dQTu31QRWclgR/dUYVwubvCIMPP8zunN2C36ujoZH+AdIFmDFvGFJhrghVUZ+1egQHBfrnUNSDNLGJpTN+NvOa9bRZVgZ7BPCkVYTMOzhEAwhfOC/PYZIZf0TPCU33glS24Mg/cjtiV4QXAFSWkluKzgQ/eOTyBd8O9ycTTv8/bBxsPVGKcCPls2nFspFlSG9VQuc1sCAVLWEK0w/FBW/3FHN26Y5mq4R5Byvnj7Hrr4r4yVICf6esUhc9WgtVJ6qqOmAIdD3oaVY=
  app: group2-ita06-ezticket-frontend
  on:
    repo: Group-2-ezTicket/ezTicket-frontend
