language: node_js
node_js:
- '12'
script:
- npm run build
branches:
    only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: N6iX2Gv30vTZoLNvO35W1mTy+k/0FxnqMJFcsBRYa/vMPbQPz8tbsEE+ps+548MmsOcIZYeSetEIjUlBfZliQYAaSMwzFR3UsAKE3JTrUYuMtINi6C5aVquvLGB02po+ZqZseHyE0z6GhKu2VfBGHyWcD3+Xeg+ed9e3iMY7i/kV6vMeN5Oj0knUmBjTybZtpuQTXOTxS+WkK4bw3tF0zYIP0tNh7t2Df6fKuZdA1y+tq3IAQbo7SLce87PhO5V8acUGex6eJDkhkH2gO9eP8vUdN8JB/CglBB7XB6BjYHt7m+AesNeWiOUmQmW5C7Kx5N2IlMF63qaxWBz5/SHL9IcrgCFxQFF54CmXGIIZ93xqHb66GwkmKGLdrxdM2TjOAvzIUw4WCBYyZuqmGYll90IxurUVeNh7Q07pB3m8jaTIWnKpp/wUuSsZfdNj6cOIkwtPyZkv6Urqv1Iwf3Hm0+ivn5vKyqZC9zxp+xYj4tnTEHe8sO7DGvjqzwpC8ZjT7JnMw0aoIhX8Ib4rzLBA5COWjjJGjl1az3iydB8892TNP1Fsur7NfwZNVcKBz6OITb5tQU+TyCLt4NJmwPY0nyjqBRPYqE18sWuwcLiL9LJM2e7qz1KBqj8fqGd0TToyUTfK/XgDgdghCery0cZrJtls+ULY8gzhE7x+1kBF9wM=
  app: group2-ita06-ezticket-frontend
  on:
    branch: main
    repo: Group-2-ezTicket/ezTicket-frontend
