language: java
dist: trusty
jdk:
- oraclejdk8
before_script:
- "./gradlew test"
script:
- "./gradlew build"
branches:
  only:
    - main
deploy:
  provider: heroku
  api_key:
    secure: Qrhf8gPF4vCcma8QfO7TyzMs6Hyff5EUr0sXUG7aTZnnCy8re3/KteBFtbZNvEvFi6XwVZ5Jkl6sdBpqGM8NkLxozUzNW/DV9vcEHoMIXmlVq9stCQxlsFbO87z8R6hssr7MzQKeExyPcyLhaz7/LjmN+RB2twcmJp8eQryEM5K3NlkwiFk+L1uaA6sUny7ke6op+10tLDBT8bBDUDMAbcPLGNdcbfpBAUfq0YNjCIu4y3S1v1ajNVoLOVQkHzX+4UqrEohbeCh0ixnsc89LVglv7cHCxT8WyeT8bfrFGQK4oOqor4HJStEmT1UiL3cSzpxNP5FG9O/8yI2HDzNm8GtgJMbxj/zVC3hY+phZmtF6ieZILDirLJNvY5PhVxDhjUh8not5Yqj66nck2a3WZw4brDtO4zk9+QMSughLQ1cA1o6Ykrf9eHTkLXSkn+f3mApUbNfCo3BS29LjWslNMSw3MaHHEt1mr75kmgbySfHuWf1dEhJsa+leaFK/iLriO6jotZU9Z00Qfy5jOHQYQ//GRIx2UW0zmwN9CBLqLTfuZV9Y3Vbw2BtqrHtNK6BUaY9TVE/hj9IbPy+obr6bz4vb85t6cWuNsaZSNEcWxMbWF1uPUh9eh0SxihPETDXeLktTplLLyy+Jkq0qaoNMyDGQ+XT3GLeTG1Bz/xiBOiw=
  app: group2-ita06-ezticket-frontend
  on:
    repo: Group-2-ezTicket/ezTicket-frontend
